Feature/mysql 8 support
cloudfoundry/backup-and-restore-sdk-release pull request #696
Opened 2022-08-29 23:41 UTC by ohkyle

This PR is to add support for mysql 8.0 to BBR. We would like access to CI so we can make changes as necessary.

- Compiling mysql 8 for xenial is not support at the moment. We present the user with an error message if they do try to backup a mysql 8.0 database with bbr compiled against a xenial stemcell.
- [reference slack thread](https://vmware.slack.com/archives/C01DXEYRKRU/p1660603529655749)

2022-08-31 21:25 UTC, dsboulder requested changes
I'm seeing a few places where we might be dropping coverage for mysql 5.7 in favor of 8, such as the autobump. We need to keep 5.7 and 8.0 up-to-date for some period of time while folks switch over (so at LEAST late 2023 when 5.7 goes out of community support)

2022-08-31 22:26 UTC, ohkyle commented
@dsboulder 

No it will continue bumping mysql 5.7. 

Lines like 
```
export DOWNLOADED_FILENAME='mysql-${VERSION/8.0/boost-8.0}.tar.gz'
```

will conditionally add a boost prefix when mysql 8.0 is detected. If the version is 5.7 it does nothing.

See this [slack thread](https://vmware.slack.com/archives/C4XV7DLN6/p1661984327607049?thread_ts=1661980949.655509&cid=C4XV7DLN6) for more context.

2022-08-31 23:17 UTC, ohkyle commented
[bc000e92-f3b5-4170-b934-876706febc01.pdf](https://github.com/cloudfoundry/backup-and-restore-sdk-release/files/9465645/bc000e92-f3b5-4170-b934-876706febc01.pdf)
Here is the signed CLA for some reason the bot will not refresh

2022-08-31 23:18 UTC, ohkyle commented
Additionally we will need access to the bosh release blob store to add the new blobs for mysql 8.0

2022-08-31 23:24 UTC, kimago commented
Is Kyle's above Signed CLA sufficient for you to rerun checks? If not & if you need him to instead go through the Upstream Contrib process, can you identify the specific Project Name (whether ["Third Party"](https://upstreamcontrib.eng.vmware.com/oss/#/upstreamcontrib/approvedthirdparty) or ["VMware Originated"](https://upstreamcontrib.eng.vmware.com/oss/#/upstreamcontrib/approvedvmware)) for which Kyle needs contrib-access? )

2022-09-01 14:27 UTC, totherme commented
See [this slack thread](https://vmware.slack.com/archives/C0NFRTZ36/p1662041965896639?thread_ts=1662041300.098099&cid=C0NFRTZ36). I'm going to close this PR and open a new one from a not-a-fork so that our CI can run it.

2022-09-01 14:27 UTC, closed without merging